const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#stage'), ctx=canvas.getContext('2d'), map=$('#spacingMap'), mctx=map.getContext('2d');
const controls={tempo:$('#tempo'),decay:$('#decay'),spacing:$('#spacing'),squash:$('#squash'),impact:$('#impact')};
const defaults={tempo:.95,decay:78,spacing:2,squash:48,impact:4};
let fps=12,playbackRate=1,pathMode='vertical',arcCount=3,verticalLoop='constant',pathPoints={start:{x:.16,y:.70},apex:{x:.273,y:.20},end:{x:.84,y:.70}},dragPoint=null;
const presets={rubber:{tempo:.95,decay:78,spacing:2,squash:48,impact:4},basketball:{tempo:.82,decay:68,spacing:2,squash:18,impact:2},bowling:{tempo:1.35,decay:38,spacing:2,squash:2,impact:1}};
const lessons={
 timing:{title:'Timing places the beats.',copy:'The ground contacts are the accents of the action. Move those contacts closer together or farther apart and the rhythm—and apparent weight—changes.',try:'Drag <b>Bounce timing</b> from quick to slow. Notice that every drawing has more screen time, even before its path changes.',note:'The impact frames set the rhythm of the action.',prompt:['If the impact frames move closer together, does the ball feel lighter or heavier?','Can two balls share the same path but communicate different weight?','Where are the accents—the “boinks”—in this animation?']},
 spacing:{title:'Spacing shapes the motion.',copy:'Timing can remain identical while the distance travelled from frame to frame changes. Close drawings create slow movement; wide gaps create speed.',try:'Choose <b>Even</b>, then <b>Gravity</b>. The bounce timing stays fixed, but one floats while the other accelerates.',note:'Close at the apex. Wide on the fast fall.',prompt:['If the impact frames stay fixed, what can spacing alone change?','Where should drawings cluster at the top of the arc?','Why does even spacing make the ball feel mechanical?']},
 squash:{title:'Shape follows force.',copy:'Stretch supports the fast fall; squash accents the collision. The normal shape returns around the slower apex. Material determines how much is believable.',try:'Compare <b>Bowling</b> with <b>Rubber</b>. Too much deformation makes every material feel soft.',note:'Stretch in motion. Squash at impact. Recover at the apex.',prompt:['How much squash can this material support before it feels rubbery?','Which matters more here: strong spacing or strong deformation?','What happens if the ball squashes for too many frames?']}
};
const lessonSources={
 timing:'Further reading: Richard Williams, The Animator\'s Survival Kit, “It’s All in the Timing and the Spacing,” printed pp. 35–37 (PDF pp. 42–44).',
 spacing:'Further reading: Richard Williams, The Animator\'s Survival Kit, “It’s All in the Timing and the Spacing,” printed pp. 35–39 (PDF pp. 42–46).',
 squash:'Further reading: Richard Williams, The Animator\'s Survival Kit, bouncing-ball discussion, printed pp. 38–39 (PDF pp. 45–46).'
};
let focus='timing',playing=true,frame=0,last=performance.now(),compare=false,promptIndex=0;
function value(name){return +controls[name].value}
function resize(){const d=devicePixelRatio||1;for(const c of [canvas,map]){const r=c.getBoundingClientRect();c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);c.getContext('2d').setTransform(d,0,0,d,0,0)}draw()}
function ease(u,mode){if(mode===0)return u;if(mode===1)return u<.5?2*u*u:1-Math.pow(-2*u+2,2)/2;return .5-.5*Math.cos(Math.PI*u)}
function arcCycleSeconds(tempo=value('tempo'),retain=value('decay')/100){let cycle=0,height=1;for(let i=0;i<arcCount;i++){cycle+=tempo*Math.sqrt(Math.max(height,.12));height*=retain}return cycle+Math.max(.9,tempo*.9)}
function timelineFrames(){return Math.max(1,Math.ceil(fps*(pathMode==='arc'?arcCycleSeconds():6)))}
function stateAt(f,override={}){const rate=override.fps??fps;let t=f/rate;const tempo=override.tempo??value('tempo'),retain=pathMode==='vertical'&&verticalLoop==='constant'?1:(override.decay??value('decay'))/100,mode=override.spacing??value('spacing');let elapsed=t,bounce=0,height=1,phase=0,duration=tempo,rollDuration=Math.max(.9,tempo*.9);if(pathMode==='arc')elapsed=t%arcCycleSeconds(tempo,retain)
 while(elapsed>=duration&&bounce<(pathMode==='arc'?arcCount:12)){elapsed-=duration;bounce++;height*=retain;duration=tempo*Math.sqrt(Math.max(height,.12))}
 if(pathMode==='arc'&&bounce===arcCount){phase=Math.min(1,elapsed/rollDuration);return{y:0,bounce:arcCount-1,height:0,phase,contact:.5,duration:rollDuration,rolling:true}}
 phase=Math.min(1,elapsed/duration);const u=ease(phase,mode);let shape=mode===0?1-Math.abs(2*phase-1):mode===1?Math.sin(Math.PI*u):4*phase*(1-phase),y=shape*height;const contact=Math.min(phase,1-phase);return{y,bounce,height,phase,contact,duration}}
function drawBall(c,x,y,r,st,alpha=1,override={},rotation=0){const amount=st.rolling?0:(override.squash??value('squash'))/100,impactFrames=override.impact??value('impact');const impactWindow=Math.min(.18,impactFrames/(st.duration*(override.fps??fps)));const squash=Math.max(0,1-st.contact/impactWindow);const speed=Math.abs(Math.cos(Math.PI*ease(st.phase,override.spacing??value('spacing'))));const stretch=amount*speed*(1-squash);let sx=1-stretch*.34,sy=1+stretch*.58;sx+=amount*squash*.65;sy-=amount*squash*.55;sy=Math.max(.42,sy);sx=1/sy*.98;
 // Anchor impact deformation at the ball's lowest point so squash never floats above the ground plane.
 const contactAnchor=r*(1-sy)*squash;
 c.save();c.globalAlpha=alpha;c.translate(x,y+contactAnchor);c.scale(sx,sy);c.beginPath();c.arc(0,0,r,0,Math.PI*2);const g=c.createRadialGradient(-r*.35,-r*.45,r*.1,0,0,r);g.addColorStop(0,'#fffdf9');g.addColorStop(.72,'#ffe4d8');g.addColorStop(1,'#ffc8b7');c.fillStyle=g;c.fill();c.strokeStyle='#6f281d';c.lineWidth=Math.max(3.5,r*.11);c.stroke();
 // A rotating diameter makes horizontal travel read as rolling while retaining the ball's volume.
 c.save();c.beginPath();c.arc(0,0,r*.96,0,Math.PI*2);c.clip();c.rotate(rotation);c.beginPath();c.moveTo(-r*.9,0);c.lineTo(r*.9,0);c.strokeStyle='rgba(91,27,19,.62)';c.lineWidth=Math.max(1.5,r*.055);c.stroke();c.restore();
 c.beginPath();c.arc(-r*.28,-r*.32,r*.13,0,Math.PI*2);c.fillStyle='rgba(255,255,255,.72)';c.fill();c.restore()}
function pathPosition(st,w,h,side){const origin=side==='right'?w*.5:0,scale=side?w*.5:w;if(pathMode==='vertical')return{x:origin+scale*.5,height:h*.48};if(st.rolling)return{x:origin+scale*(pathPoints.end.x+(1.16-pathPoints.end.x)*st.phase),height:h*(pathPoints.start.y-pathPoints.apex.y)};const span=pathPoints.end.x-pathPoints.start.x,segment=span/arcCount,a=pathPoints.start.x+segment*st.bounce,d=a+segment,bias=Math.max(.15,Math.min(.85,(pathPoints.apex.x-pathPoints.start.x)/Math.max(segment,.01))),b=a+segment*bias,u=st.phase,v=1-u,controlX=2*b-(a+d)/2;return{x:origin+scale*(v*v*a+2*v*u*controlX+u*u*d),height:h*(pathPoints.start.y-pathPoints.apex.y)}}
function drawPathGuide(c,w,h,side){if(pathMode!=='arc'||side)return;const p=pathPoints,retain=value('decay')/100,span=p.end.x-p.start.x,segment=span/arcCount,bias=Math.max(.15,Math.min(.85,(p.apex.x-p.start.x)/Math.max(segment,.01)));c.save();c.strokeStyle='rgba(29,110,104,.42)';c.lineWidth=1.5;c.setLineDash([5,6]);c.beginPath();c.moveTo(p.start.x*w,p.start.y*h);for(let i=0;i<arcCount;i++){const a=p.start.x+segment*i,d=a+segment,b=a+segment*bias,apexY=p.start.y-(p.start.y-p.apex.y)*Math.pow(retain,i),control={x:2*b-(a+d)/2,y:2*apexY-p.start.y};c.quadraticCurveTo(control.x*w,control.y*h,d*w,p.start.y*h)}c.lineTo(w*1.05,p.start.y*h);c.stroke();c.setLineDash([]);for(let i=1;i<arcCount;i++){c.beginPath();c.arc((p.start.x+segment*i)*w,p.start.y*h,4,0,Math.PI*2);c.fillStyle='rgba(29,110,104,.55)';c.fill()}for(const [name,pt] of Object.entries(p)){c.beginPath();c.arc(pt.x*w,pt.y*h,7,0,Math.PI*2);c.fillStyle=name==='apex'?'#f3b840':'#1d6e68';c.fill();c.strokeStyle='white';c.lineWidth=2;c.stroke()}c.restore()}
 function drawScene(c,f,opts={},side=null){const w=canvas.clientWidth,h=canvas.clientHeight,ground=h*.70,r=Math.min(w,h)*.058,st=stateAt(f,opts);let left=side==='right'?w*.55:w*.08,right=side==='left'?w*.45:w*.92;if(!side){left=w*.08;right=w*.92}const pos=pathPosition(st,w,h,side),x=pos.x,y=ground-r-st.y*pos.height,pathOrigin=side==='right'?w*.5:0,pathScale=side?w*.5:w,travel=pathMode==='vertical'?0:x-(pathOrigin+pathScale*pathPoints.start.x);drawPathGuide(c,w,h,side);
 c.save();if(side){c.beginPath();c.rect(side==='left'?0:w/2,0,w/2,h);c.clip()}c.strokeStyle='rgba(23,33,31,.18)';c.setLineDash([4,7]);c.beginPath();c.moveTo(left,ground);c.lineTo(right,ground);c.stroke();c.setLineDash([]);
 if($('#onionToggle').checked){for(let k=-5;k<=5;k++){if(k===0)continue;const of=Math.max(0,f+k),os=stateAt(of,opts),op=pathPosition(os,w,h,side),ot=pathMode==='vertical'?0:op.x-(pathOrigin+pathScale*pathPoints.start.x);drawBall(c,op.x,ground-r-os.y*op.height,r,os,.11,opts,ot/r*.35)}}
 c.beginPath();c.ellipse(x,ground+5,r*(1.1+st.y*.5),r*.22,0,0,Math.PI*2);c.fillStyle=`rgba(37,45,41,${.18-st.y*.08})`;c.fill();drawBall(c,x,y,r,st,1,opts,travel/r*.35);c.restore()}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);if(compare){drawScene(ctx,frame,{...defaults,squash:0},'left');drawScene(ctx,frame,{},'right');ctx.fillStyle='rgba(23,33,31,.18)';ctx.fillRect(w/2,0,1,h);ctx.font='700 10px Inter, sans-serif';ctx.fillStyle='#53615e';ctx.fillText('A · BASELINE',18,h-22);ctx.fillText('B · CURRENT',w/2+18,h-22)}else drawScene(ctx,frame);drawMap()}
function drawMap(){const w=map.clientWidth,h=map.clientHeight;mctx.clearRect(0,0,w,h);const base=h-25,n=17,r=8;mctx.strokeStyle='#d8d8d0';mctx.beginPath();mctx.moveTo(18,base);mctx.lineTo(w-18,base);mctx.stroke();for(let i=0;i<n;i++){const phase=i/(n-1),u=ease(phase,value('spacing')),y=Math.sin(Math.PI*u)*(h-55),x=22+(w-44)*phase;const fast=Math.abs(Math.cos(Math.PI*u));mctx.globalAlpha=.28+.72*fast;mctx.fillStyle=fast>.55?'#ef5b3f':'#f3b840';mctx.beginPath();mctx.arc(x,base-y,r,0,Math.PI*2);mctx.fill();mctx.globalAlpha=1;mctx.fillStyle='#52605d';mctx.font='8px Inter, sans-serif';mctx.textAlign='center';mctx.fillText(i+1,x,base+15)}}
function syncTimeline(){const total=timelineFrames();$('#scrubber').max=total-1;if(frame>=total)frame=0;$('#scrubber').value=Math.floor(frame)}
function updateLabels(){const mode=['Even','Soft ease','Gravity'][value('spacing')];$('#tempoOut').value=value('tempo').toFixed(2)+' s';$('#decayOut').value=value('decay')+'%';$('#spacingOut').value=mode;$('#squashOut').value=value('squash')+'%';$('#impactOut').value=value('impact')+' fr';$('#motionLabel').textContent=`${mode} · ${value('tempo').toFixed(2)} s beat`;syncTimeline();draw()}
function setFocus(name){focus=name;$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.focus===name));$$('.control-group[data-groups]').forEach(g=>g.classList.toggle('hidden',!g.dataset.groups.includes(name)));const l=lessons[name];$('#controlTitle').textContent={timing:'Timing & rhythm',spacing:'Spacing & easing',squash:'Squash & stretch'}[name];$('#lessonTitle').textContent=l.title;$('#lessonCopy').textContent=l.copy;$('#tryThis').innerHTML=l.try;$('#sourceNote').textContent=lessonSources[name];$('#stageNote').innerHTML=`<strong>${name==='squash'?'Squash & stretch':name}</strong><span>${l.note}</span>`;promptIndex=0;$('#promptText').textContent=l.prompt[0]}
function setValues(v){Object.entries(v).forEach(([k,x])=>controls[k]&&(controls[k].value=x));updateLabels()}
function setFps(rate){const seconds=frame/fps;fps=rate;frame=seconds*fps;syncTimeline();$('#fpsOut').value=fps+' fps';$$('[data-fps]').forEach(b=>b.classList.toggle('active',+b.dataset.fps===fps));draw()}
function setPlayback(rate){playbackRate=rate;$('#speedOut').value=rate===1?'Normal':'¼ speed';$$('[data-speed]').forEach(b=>b.classList.toggle('active',+b.dataset.speed===rate))}
function setVerticalLoop(mode){verticalLoop=mode;$('#loopOut').value=mode==='constant'?'Constant':'Decaying';$$('[data-loop]').forEach(b=>b.classList.toggle('active',b.dataset.loop===mode));draw()}
function setPath(mode){pathMode=mode;$('#pathOut').value=mode==='vertical'?'Vertical':'Arc';$$('[data-path]').forEach(b=>b.classList.toggle('active',b.dataset.path===mode));$('#pathHelp').textContent=mode==='arc'?'Drag the overall start, first apex, and end points. Intermediate decaying arcs are generated automatically.':'The ball remains centred on a straight vertical path.';$('#verticalLoopGroup').classList.toggle('hidden',mode!=='vertical');$('#arcCountGroup').classList.toggle('hidden',mode!=='arc');$('#canvasWrap').classList.toggle('path-editing',mode==='arc');syncTimeline();draw()}
function setArcCount(count){const oldSegment=(pathPoints.end.x-pathPoints.start.x)/arcCount,bias=Math.max(.15,Math.min(.85,(pathPoints.apex.x-pathPoints.start.x)/Math.max(oldSegment,.01)));arcCount=count;pathPoints.apex.x=pathPoints.start.x+(pathPoints.end.x-pathPoints.start.x)/arcCount*bias;$('#arcCount').value=count;$('#arcCountOut').value=count;frame=0;syncTimeline();draw()}
function tick(now){const total=timelineFrames();if(playing){const dt=Math.min(100,now-last);frame=(frame+dt/1000*fps*playbackRate)%total;$('#scrubber').value=Math.floor(frame)}last=now;$('#frameReadout').textContent=`Frame ${String(Math.floor(frame)+1).padStart(3,'0')} / ${total}`;$('#timeReadout').textContent=(frame/fps).toFixed(2)+' s';draw();requestAnimationFrame(tick)}
function activatePreset(name){$$('.preset').forEach(p=>p.classList.toggle('active',p.dataset.preset===name));setValues(presets[name])}
Object.values(controls).forEach(x=>x.addEventListener('input',()=>{$$('.preset').forEach(p=>p.classList.remove('active'));updateLabels()}));$$('.tab').forEach(b=>b.onclick=()=>setFocus(b.dataset.focus));$$('.preset').forEach(b=>b.onclick=()=>activatePreset(b.dataset.preset));
$('#playBtn').onclick=()=>{playing=!playing;$('#playBtn').textContent=playing?'Ⅱ':'▶';$('#playBtn').ariaLabel=playing?'Pause animation':'Play animation'};
function step(d){playing=false;$('#playBtn').textContent='▶';const total=timelineFrames();frame=(Math.floor(frame)+d+total)%total;$('#scrubber').value=frame;draw()}$('#prevFrame').onclick=()=>step(-1);$('#nextFrame').onclick=()=>step(1);$('#scrubber').oninput=e=>{playing=false;$('#playBtn').textContent='▶';frame=+e.target.value;draw()};
$('#compareBtn').onclick=()=>{compare=!compare;$('#compareBtn').textContent=compare?'Exit compare':'A/B compare';draw()};$('#onionToggle').onchange=draw;$('#fullscreenBtn').onclick=()=>$('#canvasWrap').requestFullscreen?.();
$('#resetAll').onclick=()=>{setValues(defaults);setFps(12);setPlayback(1);setVerticalLoop('constant');arcCount=3;pathPoints={start:{x:.16,y:.70},apex:{x:.273,y:.20},end:{x:.84,y:.70}};setArcCount(3);setPath('vertical');setFocus('timing');compare=false;$('.compare').textContent='A/B compare';$$('.preset').forEach(p=>p.classList.toggle('active',p.dataset.preset==='rubber'));$('#controlsCard').scrollTop=0};$('#resetFocus').onclick=()=>setValues(defaults);$('#newPrompt').onclick=()=>{const p=lessons[focus].prompt;promptIndex=(promptIndex+1)%p.length;$('#promptText').textContent=p[promptIndex]};
addEventListener('keydown',e=>{if(e.code==='Space'&&!/INPUT|BUTTON/.test(e.target.tagName)){e.preventDefault();$('#playBtn').click()}if(e.key==='ArrowLeft')step(-1);if(e.key==='ArrowRight')step(1)});addEventListener('resize',resize);
$$('[data-fps]').forEach(b=>b.onclick=()=>setFps(+b.dataset.fps));$$('[data-speed]').forEach(b=>b.onclick=()=>setPlayback(+b.dataset.speed));$$('[data-path]').forEach(b=>b.onclick=()=>setPath(b.dataset.path));$$('[data-loop]').forEach(b=>b.onclick=()=>setVerticalLoop(b.dataset.loop));
$('#arcCount').oninput=e=>setArcCount(+e.target.value);
function pointerPosition(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}
canvas.addEventListener('pointerdown',e=>{if(pathMode!=='arc'||compare)return;const p=pointerPosition(e);dragPoint=Object.entries(pathPoints).find(([,pt])=>Math.hypot((pt.x-p.x)*canvas.clientWidth,(pt.y-p.y)*canvas.clientHeight)<18)?.[0]??null;if(dragPoint){playing=false;canvas.setPointerCapture(e.pointerId)}});
canvas.addEventListener('pointermove',e=>{if(!dragPoint)return;const p=pointerPosition(e),oldSegment=(pathPoints.end.x-pathPoints.start.x)/arcCount,bias=Math.max(.15,Math.min(.85,(pathPoints.apex.x-pathPoints.start.x)/Math.max(oldSegment,.01)));if(dragPoint==='start'){pathPoints.start.x=Math.max(.06,Math.min(pathPoints.end.x-.18,p.x));pathPoints.apex.x=pathPoints.start.x+(pathPoints.end.x-pathPoints.start.x)/arcCount*bias}else if(dragPoint==='end'){pathPoints.end.x=Math.max(pathPoints.start.x+.18,Math.min(.94,p.x));pathPoints.apex.x=pathPoints.start.x+(pathPoints.end.x-pathPoints.start.x)/arcCount*bias}else{const segment=(pathPoints.end.x-pathPoints.start.x)/arcCount;pathPoints.apex.x=Math.max(pathPoints.start.x+segment*.15,Math.min(pathPoints.start.x+segment*.85,p.x));pathPoints.apex.y=Math.max(.08,Math.min(.58,p.y))}draw()});
canvas.addEventListener('pointerup',e=>{if(dragPoint)canvas.releasePointerCapture(e.pointerId);dragPoint=null});
function applyStudentRequest(question){const q=question.toLowerCase(),changes=[];if(/12\s*fps|twelve\s*(fps|frames)/.test(q)){setFps(12);changes.push('set the animation to 12 fps')}else if(/24\s*fps|twenty.?four\s*(fps|frames)/.test(q)){setFps(24);changes.push('set the animation to 24 fps')}if(/quarter speed|¼ speed|slow motion|slow-mo/.test(q)){setPlayback(.25);changes.push('switched playback to quarter speed')}else if(/normal (playback|speed)|full speed/.test(q)){setPlayback(1);changes.push('restored normal playback speed')}if(/vertical|up and down|straight up/.test(q)){setPath('vertical');changes.push('changed the path to a vertical bounce')}else if(/arc path|curved path|multiple arcs|arc bounce/.test(q)){setPath('arc');changes.push('changed the path to editable arcs')}if(/constant height|same height|perpetual|loop forever|even height/.test(q)){setPath('vertical');setVerticalLoop('constant');changes.push('made the vertical bounce repeat at a constant height')}else if(/decay|decreasing height|lose energy|smaller bounce/.test(q)){setVerticalLoop('decay');changes.push('enabled decreasing bounce height')}for(const name of ['rubber','basketball','bowling'])if(q.includes(name)){activatePreset(name);changes.push(`loaded the ${name} preset`);break}if(/show (the )?(spacing|onion)|onion skin/.test(q)){$('#onionToggle').checked=true;changes.push('turned on the spacing drawings');draw()}else if(/hide (the )?(spacing|onion)/.test(q)){ $('#onionToggle').checked=false;changes.push('hid the spacing drawings');draw()}if(/increase|more|wider|exaggerate/.test(q)&&/spacing|gap/.test(q)){controls.spacing.value=2;controls.tempo.value=Math.max(+controls.tempo.min,value('tempo')-.15);setFocus('spacing');updateLabels();changes.push('made the beat quicker so the frame-to-frame gaps become wider and selected gravity spacing')}else if(/decrease|less|closer|reduce/.test(q)&&/spacing|gap/.test(q)){controls.tempo.value=Math.min(+controls.tempo.max,value('tempo')+.15);setFocus('spacing');updateLabels();changes.push('slowed the beat so the frame-to-frame gaps become closer')}if(/increase|more|exaggerate/.test(q)&&/squash|stretch|deformation/.test(q)){controls.squash.value=Math.min(+controls.squash.max,value('squash')+10);setFocus('squash');updateLabels();changes.push('increased squash and stretch')}else if(/decrease|less|reduce/.test(q)&&/squash|stretch|deformation/.test(q)){controls.squash.value=Math.max(+controls.squash.min,value('squash')-10);setFocus('squash');updateLabels();changes.push('reduced squash and stretch')}const count=q.match(/(?:show|use|make)?\s*([1-6])\s*(?:arc|bounce)/);if(count){setPath('arc');setArcCount(+count[1]);changes.push(`set the path to ${count[1]} arc bounce${count[1]==='1'?'':'s'}`)}return changes}
function answerFromWilliams(question){const q=question.toLowerCase(),ideas=[],pages=new Set();if(/timing|beat|contact|frame|fast|slow|duration/.test(q)){ideas.push('place the important contact beats first, because changing when those beats occur changes the rhythm and apparent weight');pages.add('35–37')}if(/spacing|apex|drawing|close|far apart|slow in|slow out|ease|gravity|fall|rise|gap/.test(q)){ideas.push('shape the movement between those beats with close drawings where the action slows and wider gaps where it accelerates');pages.add('35–39')}if(/squash|stretch|deform|rubber|shape|impact/.test(q)){ideas.push('use deformation to support force—stretch around the fast movement and squash at impact—while preserving volume and returning to the normal shape in the slower part of the arc');pages.add('38–39')}if(/weight|heavy|light|energy|material|bowling|basketball/.test(q)){ideas.push('let timing and spacing establish weight before adding deformation, since a hard or heavy object should not behave as though everything is soft rubber');pages.add('35–39')}if(/arc|path|bounce|ball|roll/.test(q)){ideas.push('judge the path and the changing frame-to-frame gaps together, because a convincing arc still depends on acceleration into contact and deceleration toward the apex');pages.add('35–39')}if(!ideas.length){ideas.push('start by separating the contact timing from the frame-to-frame spacing, then check whether the drawings clearly accelerate, slow, and communicate weight');pages.add('35–39')}const context=ideas.length>1?ideas.slice(0,-1).join('; ')+`; and ${ideas.at(-1)}`:ideas[0];return`A useful way to explore that is to ${context}. That is my friendly, contextual application of Williams’ bouncing-ball discussion rather than a direct quotation. You can compare it with printed pp. ${[...pages].join(', ')}.`}
$('#studentQuestionForm').onsubmit=e=>{e.preventDefault();const question=$('#studentQuestion').value.trim();if(!question)return;const changes=applyStudentRequest(question),confirmation=changes.length?`I’ve ${changes.join(', and ')}. Watch the animation now and compare what changed. `:'';$('#sourceAnswer').innerHTML='<strong>Let’s explore it · Williams pp. 35–39</strong><span></span>';$('#sourceAnswer span').textContent=`Great question! ${confirmation}${answerFromWilliams(question)}`};
$('#controlsDockToggle').onclick=()=>{const collapsed=$('#controlsCard').classList.toggle('collapsed');$('#workspaceGrid').classList.toggle('controls-collapsed',collapsed);$('#controlsDockToggle').setAttribute('aria-expanded',String(!collapsed));$('#controlsDockToggle').setAttribute('aria-label',collapsed?'Expand live controls':'Collapse live controls');$('#controlsDockToggle').title=collapsed?'Expand live controls':'Collapse live controls';requestAnimationFrame(resize)};
setFocus('timing');setFps(12);setPlayback(1);setVerticalLoop('constant');setArcCount(3);setPath('vertical');activatePreset('rubber');$('#controlsCard').scrollTop=0;updateLabels();resize();requestAnimationFrame(tick);
