const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#stage'), ctx=canvas.getContext('2d'), map=$('#spacingMap'), mctx=map.getContext('2d');
const controls={tempo:$('#tempo'),decay:$('#decay'),spacing:$('#spacing'),squash:$('#squash'),impact:$('#impact')};
const defaults={tempo:1,decay:72,spacing:2,squash:32,impact:3};
let fps=24,pathMode='arc',pathPoints={start:{x:.16,y:.70},apex:{x:.50,y:.20},end:{x:.84,y:.70}},dragPoint=null;
const presets={rubber:{tempo:.95,decay:78,spacing:2,squash:48,impact:4},basketball:{tempo:.82,decay:68,spacing:2,squash:18,impact:2},bowling:{tempo:1.35,decay:38,spacing:2,squash:2,impact:1}};
const lessons={
 timing:{title:'Timing places the beats.',copy:'The ground contacts are the accents of the action. Move those contacts closer together or farther apart and the rhythm—and apparent weight—changes.',try:'Drag <b>Bounce timing</b> from quick to slow. Notice that every drawing has more screen time, even before its path changes.',note:'The impact frames set the rhythm of the action.',prompt:['If the impact frames move closer together, does the ball feel lighter or heavier?','Can two balls share the same path but communicate different weight?','Where are the accents—the “boinks”—in this animation?']},
 spacing:{title:'Spacing shapes the motion.',copy:'Timing can remain identical while the distance travelled from frame to frame changes. Close drawings create slow movement; wide gaps create speed.',try:'Choose <b>Even</b>, then <b>Gravity</b>. The bounce timing stays fixed, but one floats while the other accelerates.',note:'Close at the apex. Wide on the fast fall.',prompt:['If the impact frames stay fixed, what can spacing alone change?','Where should drawings cluster at the top of the arc?','Why does even spacing make the ball feel mechanical?']},
 squash:{title:'Shape follows force.',copy:'Stretch supports the fast fall; squash accents the collision. The normal shape returns around the slower apex. Material determines how much is believable.',try:'Compare <b>Bowling</b> with <b>Rubber</b>. Too much deformation makes every material feel soft.',note:'Stretch in motion. Squash at impact. Recover at the apex.',prompt:['How much squash can this material support before it feels rubbery?','Which matters more here: strong spacing or strong deformation?','What happens if the ball squashes for too many frames?']}
};
let focus='timing',playing=true,frame=0,last=performance.now(),compare=false,promptIndex=0;
function value(name){return +controls[name].value}
function resize(){const d=devicePixelRatio||1;for(const c of [canvas,map]){const r=c.getBoundingClientRect();c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);c.getContext('2d').setTransform(d,0,0,d,0,0)}draw()}
function ease(u,mode){if(mode===0)return u;if(mode===1)return u<.5?2*u*u:1-Math.pow(-2*u+2,2)/2;return .5-.5*Math.cos(Math.PI*u)}
function stateAt(f,override={}){const rate=override.fps??fps,t=(f/rate),tempo=override.tempo??value('tempo'),retain=(override.decay??value('decay'))/100,mode=override.spacing??value('spacing');let elapsed=t,bounce=0,height=1,phase=0,duration=tempo;
 while(elapsed>=duration&&bounce<12){elapsed-=duration;bounce++;height*=retain;duration=tempo*Math.sqrt(Math.max(height,.12))}
 phase=Math.min(1,elapsed/duration);const u=ease(phase,mode);let y=Math.sin(Math.PI*u)*height;const contact=Math.min(phase,1-phase);return{y,bounce,height,phase,contact,duration}}
function drawBall(c,x,y,r,st,alpha=1,override={},rotation=0){const amount=(override.squash??value('squash'))/100,impactFrames=override.impact??value('impact');const impactWindow=Math.min(.18,impactFrames/(st.duration*(override.fps??fps)));const squash=Math.max(0,1-st.contact/impactWindow);const speed=Math.abs(Math.cos(Math.PI*ease(st.phase,override.spacing??value('spacing'))));const stretch=amount*speed*(1-squash);let sx=1-stretch*.34,sy=1+stretch*.58;sx+=amount*squash*.65;sy-=amount*squash*.55;sy=Math.max(.42,sy);sx=1/sy*.98;
 // Anchor impact deformation at the ball's lowest point so squash never floats above the ground plane.
 const contactAnchor=r*(1-sy)*squash;
 c.save();c.globalAlpha=alpha;c.translate(x,y+contactAnchor);c.scale(sx,sy);c.beginPath();c.arc(0,0,r,0,Math.PI*2);const g=c.createRadialGradient(-r*.35,-r*.45,r*.1,0,0,r);g.addColorStop(0,'#ff8a69');g.addColorStop(.62,'#ef5b3f');g.addColorStop(1,'#bb3524');c.fillStyle=g;c.fill();c.strokeStyle='rgba(80,25,15,.28)';c.lineWidth=1;c.stroke();
 // A rotating diameter makes horizontal travel read as rolling while retaining the ball's volume.
 c.save();c.beginPath();c.arc(0,0,r*.96,0,Math.PI*2);c.clip();c.rotate(rotation);c.beginPath();c.moveTo(-r*.9,0);c.lineTo(r*.9,0);c.strokeStyle='rgba(91,27,19,.62)';c.lineWidth=Math.max(1.5,r*.055);c.stroke();c.restore();
 c.beginPath();c.arc(-r*.28,-r*.32,r*.13,0,Math.PI*2);c.fillStyle='rgba(255,255,255,.32)';c.fill();c.restore()}
function pathPosition(st,w,h,side){const origin=side==='right'?w*.5:0,scale=side?w*.5:w;if(pathMode==='vertical')return{x:origin+scale*.5,height:h*.48};const reverse=st.bounce%2===1,a=reverse?pathPoints.end:pathPoints.start,b=pathPoints.apex,d=reverse?pathPoints.start:pathPoints.end,u=st.phase,v=1-u,controlX=2*b.x-(a.x+d.x)/2;return{x:origin+scale*(v*v*a.x+2*v*u*controlX+u*u*d.x),height:h*(pathPoints.start.y-pathPoints.apex.y)}}
function drawPathGuide(c,w,h,side){if(pathMode!=='arc'||side)return;const p=pathPoints,control={x:2*p.apex.x-(p.start.x+p.end.x)/2,y:2*p.apex.y-(p.start.y+p.end.y)/2};c.save();c.strokeStyle='rgba(29,110,104,.42)';c.lineWidth=1.5;c.setLineDash([5,6]);c.beginPath();c.moveTo(p.start.x*w,p.start.y*h);c.quadraticCurveTo(control.x*w,control.y*h,p.end.x*w,p.end.y*h);c.stroke();c.setLineDash([]);for(const [name,pt] of Object.entries(p)){c.beginPath();c.arc(pt.x*w,pt.y*h,7,0,Math.PI*2);c.fillStyle=name==='apex'?'#f3b840':'#1d6e68';c.fill();c.strokeStyle='white';c.lineWidth=2;c.stroke()}c.restore()}
 function drawScene(c,f,opts={},side=null){const w=canvas.clientWidth,h=canvas.clientHeight,ground=h*.70,r=Math.min(w,h)*.058,st=stateAt(f,opts);let left=side==='right'?w*.55:w*.08,right=side==='left'?w*.45:w*.92;if(!side){left=w*.08;right=w*.92}const pos=pathPosition(st,w,h,side),x=pos.x,y=ground-r-st.y*pos.height,travel=(st.bounce+(st.bounce%2?1-st.phase:st.phase))*(right-left);drawPathGuide(c,w,h,side);
 c.save();if(side){c.beginPath();c.rect(side==='left'?0:w/2,0,w/2,h);c.clip()}c.strokeStyle='rgba(23,33,31,.18)';c.setLineDash([4,7]);c.beginPath();c.moveTo(left,ground);c.lineTo(right,ground);c.stroke();c.setLineDash([]);
 if($('#onionToggle').checked){for(let k=-5;k<=5;k++){if(k===0)continue;const of=Math.max(0,f+k),os=stateAt(of,opts),op=pathPosition(os,w,h,side),ot=(os.bounce+(os.bounce%2?1-os.phase:os.phase))*(right-left);drawBall(c,op.x,ground-r-os.y*op.height,r,os,.11,opts,-ot/r)}}
 c.beginPath();c.ellipse(x,ground+5,r*(1.1+st.y*.5),r*.22,0,0,Math.PI*2);c.fillStyle=`rgba(37,45,41,${.18-st.y*.08})`;c.fill();drawBall(c,x,y,r,st,1,opts,-travel/r);c.restore()}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);if(compare){drawScene(ctx,frame,{...defaults,squash:0},'left');drawScene(ctx,frame,{},'right');ctx.fillStyle='rgba(23,33,31,.18)';ctx.fillRect(w/2,0,1,h);ctx.font='700 10px Inter, sans-serif';ctx.fillStyle='#53615e';ctx.fillText('A · BASELINE',18,h-22);ctx.fillText('B · CURRENT',w/2+18,h-22)}else drawScene(ctx,frame);drawMap()}
function drawMap(){const w=map.clientWidth,h=map.clientHeight;mctx.clearRect(0,0,w,h);const base=h-25,n=17,r=8;mctx.strokeStyle='#d8d8d0';mctx.beginPath();mctx.moveTo(18,base);mctx.lineTo(w-18,base);mctx.stroke();for(let i=0;i<n;i++){const phase=i/(n-1),u=ease(phase,value('spacing')),y=Math.sin(Math.PI*u)*(h-55),x=22+(w-44)*phase;const fast=Math.abs(Math.cos(Math.PI*u));mctx.globalAlpha=.28+.72*fast;mctx.fillStyle=fast>.55?'#ef5b3f':'#f3b840';mctx.beginPath();mctx.arc(x,base-y,r,0,Math.PI*2);mctx.fill();mctx.globalAlpha=1;mctx.fillStyle='#52605d';mctx.font='8px Inter, sans-serif';mctx.textAlign='center';mctx.fillText(i+1,x,base+15)}}
function updateLabels(){const mode=['Even','Soft ease','Gravity'][value('spacing')];$('#tempoOut').value=value('tempo').toFixed(2)+' s';$('#decayOut').value=value('decay')+'%';$('#spacingOut').value=mode;$('#squashOut').value=value('squash')+'%';$('#impactOut').value=value('impact')+' fr';$('#motionLabel').textContent=`${mode} · ${value('tempo').toFixed(2)} s beat`;draw()}
function setFocus(name){focus=name;$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.focus===name));$$('.control-group[data-groups]').forEach(g=>g.classList.toggle('hidden',!g.dataset.groups.includes(name)));const l=lessons[name];$('#controlTitle').textContent={timing:'Timing & rhythm',spacing:'Spacing & easing',squash:'Squash & stretch'}[name];$('#lessonTitle').textContent=l.title;$('#lessonCopy').textContent=l.copy;$('#tryThis').innerHTML=l.try;$('#stageNote').innerHTML=`<strong>${name==='squash'?'Squash & stretch':name}</strong><span>${l.note}</span>`;promptIndex=0;$('#promptText').textContent=l.prompt[0]}
function setValues(v){Object.entries(v).forEach(([k,x])=>controls[k]&&(controls[k].value=x));updateLabels()}
function setFps(rate){const seconds=frame/fps;fps=rate;frame=seconds*fps;const total=fps*6;$('#scrubber').max=total-1;$('#scrubber').value=Math.floor(frame);$('#fpsOut').value=fps+' fps';$$('[data-fps]').forEach(b=>b.classList.toggle('active',+b.dataset.fps===fps));draw()}
function setPath(mode){pathMode=mode;$('#pathOut').value=mode==='vertical'?'Vertical':'Arc';$$('[data-path]').forEach(b=>b.classList.toggle('active',b.dataset.path===mode));$('#pathHelp').textContent=mode==='arc'?'Drag the three path points on the stage to set the contacts and apex.':'The ball remains centred on a straight vertical path.';$('#canvasWrap').classList.toggle('path-editing',mode==='arc');draw()}
function tick(now){const total=fps*6;if(playing){const dt=Math.min(100,now-last);frame=(frame+dt/1000*fps)%total;$('#scrubber').value=Math.floor(frame)}last=now;$('#frameReadout').textContent=`Frame ${String(Math.floor(frame)+1).padStart(3,'0')} / ${total}`;$('#timeReadout').textContent=(frame/fps).toFixed(2)+' s';draw();requestAnimationFrame(tick)}
Object.values(controls).forEach(x=>x.addEventListener('input',()=>{$$('.preset').forEach(p=>p.classList.remove('active'));updateLabels()}));$$('.tab').forEach(b=>b.onclick=()=>setFocus(b.dataset.focus));$$('.preset').forEach(b=>b.onclick=()=>{$$('.preset').forEach(p=>p.classList.toggle('active',p===b));setValues(presets[b.dataset.preset])});
$('#playBtn').onclick=()=>{playing=!playing;$('#playBtn').textContent=playing?'Ⅱ':'▶';$('#playBtn').ariaLabel=playing?'Pause animation':'Play animation'};
function step(d){playing=false;$('#playBtn').textContent='▶';const total=fps*6;frame=(Math.floor(frame)+d+total)%total;$('#scrubber').value=frame;draw()}$('#prevFrame').onclick=()=>step(-1);$('#nextFrame').onclick=()=>step(1);$('#scrubber').oninput=e=>{playing=false;$('#playBtn').textContent='▶';frame=+e.target.value;draw()};
$('#compareBtn').onclick=()=>{compare=!compare;$('#compareBtn').textContent=compare?'Exit compare':'A/B compare';draw()};$('#onionToggle').onchange=draw;$('#fullscreenBtn').onclick=()=>$('#canvasWrap').requestFullscreen?.();
$('#resetAll').onclick=()=>{setValues(defaults);setFps(24);setPath('arc');pathPoints={start:{x:.16,y:.70},apex:{x:.50,y:.20},end:{x:.84,y:.70}};setFocus('timing');compare=false;$('.compare').textContent='A/B compare';$$('.preset').forEach(p=>p.classList.remove('active'))};$('#resetFocus').onclick=()=>setValues(defaults);$('#newPrompt').onclick=()=>{const p=lessons[focus].prompt;promptIndex=(promptIndex+1)%p.length;$('#promptText').textContent=p[promptIndex]};
addEventListener('keydown',e=>{if(e.code==='Space'&&!/INPUT|BUTTON/.test(e.target.tagName)){e.preventDefault();$('#playBtn').click()}if(e.key==='ArrowLeft')step(-1);if(e.key==='ArrowRight')step(1)});addEventListener('resize',resize);
$$('[data-fps]').forEach(b=>b.onclick=()=>setFps(+b.dataset.fps));$$('[data-path]').forEach(b=>b.onclick=()=>setPath(b.dataset.path));
function pointerPosition(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}
canvas.addEventListener('pointerdown',e=>{if(pathMode!=='arc'||compare)return;const p=pointerPosition(e);dragPoint=Object.entries(pathPoints).find(([,pt])=>Math.hypot((pt.x-p.x)*canvas.clientWidth,(pt.y-p.y)*canvas.clientHeight)<18)?.[0]??null;if(dragPoint){playing=false;canvas.setPointerCapture(e.pointerId)}});
canvas.addEventListener('pointermove',e=>{if(!dragPoint)return;const p=pointerPosition(e),pt=pathPoints[dragPoint];pt.x=Math.max(.06,Math.min(.94,p.x));if(dragPoint==='apex')pt.y=Math.max(.08,Math.min(.58,p.y));draw()});
canvas.addEventListener('pointerup',e=>{if(dragPoint)canvas.releasePointerCapture(e.pointerId);dragPoint=null});
setFocus('timing');setFps(24);setPath('arc');updateLabels();resize();requestAnimationFrame(tick);
