const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const canvas=$('#stage'),ctx=canvas.getContext('2d'),map=$('#actionMap'),mctx=map.getContext('2d');
let fps=12,speed=1,frame=0,playing=true,last=performance.now(),compare=false,prompt=0;
const defaults={delay:3,flex:68,overlap:72,settle:6,height:64};
const controls={delay:$('#delay'),flex:$('#flex'),overlap:$('#overlap'),settle:$('#settle'),height:$('#height')};
const prompts=['When the ball changes direction, which part should change direction last?','At the apex, why can the tail still be moving upward?','What happens to the sense of weight when every part stops together?','How many frames should the tail need to settle after impact?'];
const lessons={follow:['The body leads. The tail catches up.','Follow through is the continuation of flexible parts after the main body changes speed or direction. Overlapping action means those parts do not start, stop, or reverse at exactly the same time.','Set Tail delay to zero, then raise it to three frames. Watch the launch, apex and landing. Which version feels more flexible?'],overlap:['Different parts carry different timing.','The base of the tail responds first because it is attached to the ball. The middle and tip respond progressively later. This successive delay creates a flexible, connected action.','Increase Overlapping drag. Pause near the apex and compare the direction of the ball with the curve of the tail.'],settle:['The action finishes in stages.','Landing is not the end of every movement. The ball contacts first; the tail continues, passes its resting position, reverses and gradually loses energy.','Increase Landing settle, then step through the final frames. Identify the first overshoot and the smaller recovery.']};
function resize(){for(const c of [canvas,map]){const d=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=Math.max(1,Math.round(r.width*d));c.height=Math.max(1,Math.round(r.height*d));c.getContext('2d').setTransform(d,0,0,d,0,0)}draw()}
function totalFrames(){return 4+22+(+controls.settle.value)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function motionAt(f){const total=totalFrames(),launch=4,flight=22,settle=+controls.settle.value;if(f<launch){const p=f/launch;return{phase:'anticipation',p,x:.32,y:0,vx:0,vy:.04*Math.sin(p*Math.PI),squash:.3*Math.sin(p*Math.PI)}}if(f<launch+flight){const p=(f-launch)/flight;return{phase:p<.14?'launch':p<.46?'rise':p<.6?'apex':p<.9?'fall':'impact',p,x:.32+.51*p,y:4*p*(1-p),vx:.51/flight,vy:(4-8*p)/flight,squash:p<.12?.22*(1-p/.12):p>.9?.3*((p-.9)/.1):0}}const p=(f-launch-flight)/settle;return{phase:p<.24?'impact':'settle',landed:true,p,x:.83,y:0,vx:0,vy:0,squash:.38*Math.exp(-p*4)*Math.abs(Math.cos(p*Math.PI*3))}}
function scenePoint(state,w,h){const ground=h*.79,box={x:w*.12,y:ground-h*.36,w:w*.22,h:h*.36},r=Math.min(w,h)*.042,arc=h*(.25+(+controls.height.value/100)*.25);if(state.phase==='anticipation')return{x:box.x+box.w-r*1.05,y:box.y-r+state.vy*h,r,ground,box};if(state.landed)return{x:w*state.x,y:ground-r+state.squash*r*.55,r,ground,box};const startY=box.y-r,endY=ground-r;return{x:w*state.x,y:startY+(endY-startY)*state.p-state.y*arc,r,ground,box}}
function tailShape(state,point,rigid=false){const delay=rigid?0:+controls.delay.value,flex=(rigid?.08:+controls.flex.value/100),drag=rigid?.05:+controls.overlap.value/100,past=motionAt(clamp(frame-delay,0,totalFrames()-1)),dx=(state.x-past.x)*point.r*14,dy=(state.y-past.y)*point.r*11;let angle=Math.atan2(-state.vy*70-dy,-state.vx*70-dx);if(state.phase==='anticipation')angle=Math.PI+(.5-state.p)*1.2;if(state.phase==='settle'||state.phase==='impact')angle=Math.PI+Math.sin(state.p*Math.PI*3)*flex*.9;const len=point.r*(2.1+flex*1.7),bend=(state.phase==='settle'?Math.sin(state.p*Math.PI*3):Math.sin((frame-delay)*.48))*point.r*flex*drag;return{angle,len,bend}}
function drawTail(c,state,p,alpha=1,rigid=false){const t=tailShape(state,p,rigid),attachX=p.x-Math.cos(t.angle)*p.r*.72,attachY=p.y-Math.sin(t.angle)*p.r*.72,tipX=attachX+Math.cos(t.angle)*t.len,tipY=attachY+Math.sin(t.angle)*t.len,normalX=-Math.sin(t.angle),normalY=Math.cos(t.angle),c1x=attachX+Math.cos(t.angle)*t.len*.35+normalX*t.bend,c1y=attachY+Math.sin(t.angle)*t.len*.35+normalY*t.bend,c2x=attachX+Math.cos(t.angle)*t.len*.76-normalX*t.bend*.7,c2y=attachY+Math.sin(t.angle)*t.len*.76-normalY*t.bend*.7;c.save();c.globalAlpha=alpha;c.strokeStyle=rigid?'#7f8986':'#1d6e68';c.lineCap='round';c.lineWidth=p.r*.58;c.beginPath();c.moveTo(attachX,attachY);c.bezierCurveTo(c1x,c1y,c2x,c2y,tipX,tipY);c.stroke();c.strokeStyle='#f7e0d7';c.lineWidth=p.r*.34;c.stroke();c.strokeStyle='rgba(29,110,104,.45)';c.lineWidth=1;for(const u of [.35,.65]){const x=attachX+(tipX-attachX)*u+normalX*t.bend*Math.sin(u*Math.PI),y=attachY+(tipY-attachY)*u+normalY*t.bend*Math.sin(u*Math.PI);c.beginPath();c.moveTo(x-normalX*p.r*.2,y-normalY*p.r*.2);c.lineTo(x+normalX*p.r*.2,y+normalY*p.r*.2);c.stroke()}c.restore()}
function drawBall(c,state,p,alpha=1,rigid=false){c.save();c.globalAlpha=alpha;c.translate(p.x,p.y);const sy=1-state.squash,sx=1+state.squash*.65;c.scale(sx,sy);const g=c.createRadialGradient(-p.r*.3,-p.r*.4,p.r*.1,0,0,p.r);g.addColorStop(0,'#fffaf5');g.addColorStop(1,rigid?'#dfe4e2':'#ffd8cc');c.fillStyle=g;c.strokeStyle=rigid?'#68736f':'#7c2c20';c.lineWidth=Math.max(3,p.r*.11);c.beginPath();c.arc(0,0,p.r,0,Math.PI*2);c.fill();c.stroke();c.restore()}
function drawScene(){const w=canvas.clientWidth,h=canvas.clientHeight,state=motionAt(frame),p=scenePoint(state,w,h);ctx.clearRect(0,0,w,h);ctx.fillStyle='#e7f0ed';ctx.fillRect(0,0,w,p.ground);ctx.fillStyle='#ece3d2';ctx.fillRect(0,p.ground,w,h-p.ground);ctx.strokeStyle='#b8ad92';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,p.ground);ctx.lineTo(w,p.ground);ctx.stroke();ctx.fillStyle='#fffdfa';ctx.strokeStyle='#17211f';ctx.lineWidth=3;ctx.fillRect(p.box.x,p.box.y,p.box.w,p.box.h);ctx.strokeRect(p.box.x,p.box.y,p.box.w,p.box.h);if($('#arcToggle').checked){ctx.setLineDash([7,8]);ctx.strokeStyle='rgba(29,110,104,.34)';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<=40;i++){const s=motionAt(4+i/40*22),q=scenePoint(s,w,h);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)}ctx.stroke();ctx.setLineDash([])}if($('#onionToggle').checked){for(const f of [4,8,14,20,25,28]){const s=motionAt(clamp(f,0,totalFrames()-1)),q=scenePoint(s,w,h);drawTail(ctx,s,q,.13);drawBall(ctx,s,q,.13)}}ctx.fillStyle='rgba(23,33,31,.13)';ctx.beginPath();ctx.ellipse(p.x,p.ground+5,p.r*1.35,p.r*.23,0,0,Math.PI*2);ctx.fill();if(compare){drawTail(ctx,state,p,.35,true);drawBall(ctx,state,p,.32,true)}drawTail(ctx,state,p,1,false);drawBall(ctx,state,p,1,false);if($('#explainToggle').checked)drawLabels(state,p,w,h);updatePhase(state)}
function drawLabels(state,p,w,h){const labels=[['BALL · PRIMARY ACTION',p.x,p.y-p.r*1.6,'#ef5b3f'],['TAIL · DELAYED RESPONSE',p.x-p.r*3.3,p.y+p.r*1.8,'#1d6e68']];ctx.font='700 10px Inter, sans-serif';ctx.textAlign='center';for(const [text,x,y,color] of labels){const width=ctx.measureText(text).width+16;ctx.fillStyle='rgba(255,253,250,.94)';ctx.fillRect(clamp(x-width/2,6,w-width-6),clamp(y-14,6,h-28),width,24);ctx.fillStyle=color;ctx.fillText(text,clamp(x,6+width/2,w-6-width/2),clamp(y+2,22,h-10))}}
function updatePhase(s){const info={anticipation:['ANTICIPATION','The body prepares. The tail has not yet received the full force.'],launch:['LAUNCH','The ball leads upward. The tail is pulled after it.'],rise:['FOLLOW THROUGH','The tail continues the launch action while the ball travels forward.'],apex:['OVERLAP AT THE APEX','The ball slows first. The tail is still catching up.'],fall:['SUCCESSIVE DRAG','The tail base turns before its middle and tip.'],impact:['IMPACT & OVERSHOOT','The ball contacts first. The tail continues past it.'],settle:['SETTLE','The tail reverses, overshoots and gradually loses energy.']}[s.phase];$('#phaseTitle').textContent=info[0];$('#phaseNote').textContent=info[1];$('#motionLabel').textContent=info[0][0]+info[0].slice(1).toLowerCase()}
function drawMap(){const w=map.clientWidth,h=map.clientHeight,total=totalFrames(),beats=[['CROUCH',2],['LAUNCH',4],['APEX',15],['IMPACT',26],['SETTLE',total-1]],delay=+controls.delay.value;mctx.clearRect(0,0,w,h);mctx.font='700 9px Inter, sans-serif';for(const [row,y,color] of [['BALL',45,'#ef5b3f'],['TAIL',98,'#1d6e68']]){mctx.fillStyle='#66716e';mctx.textAlign='left';mctx.fillText(row,4,y+3);mctx.strokeStyle='#d9d9d1';mctx.beginPath();mctx.moveTo(45,y);mctx.lineTo(w-8,y);mctx.stroke();for(const [name,f] of beats){const ff=row==='TAIL'?Math.min(total-1,f+delay):f,x=45+(w-58)*ff/(total-1);mctx.fillStyle=color;mctx.beginPath();mctx.arc(x,y,6,0,Math.PI*2);mctx.fill();mctx.fillStyle='#52605d';mctx.textAlign='center';mctx.fillText(ff+1,x,y+19);if(row==='BALL'){mctx.fillStyle='#66716e';mctx.font='700 8px Inter, sans-serif';mctx.fillText(name,x,y-13);mctx.font='700 9px Inter, sans-serif'}}}}
function draw(){drawScene();drawMap()}
function sync(){const total=totalFrames();$('#scrubber').max=total-1;frame=clamp(frame,0,total-1);$('#scrubber').value=Math.floor(frame);for(const [k,c] of Object.entries(controls)){$(`#${k}Out`).value=k==='delay'||k==='settle'?`${c.value} frames`:`${c.value}%`}draw()}
function setFps(v){fps=v;$('#fpsOut').value=`${v} fps`;$$('[data-fps]').forEach(b=>b.classList.toggle('active',+b.dataset.fps===v))}
function setSpeed(v){speed=v;$('#speedOut').value=v===1?'Normal':'¼ speed';$$('[data-speed]').forEach(b=>b.classList.toggle('active',+b.dataset.speed===v))}
function reset(){for(const [k,v] of Object.entries(defaults))controls[k].value=v;fps=12;speed=1;frame=0;compare=false;$('#compareBtn').textContent='Compare rigid tail';$('#onionToggle').checked=false;$('#explainToggle').checked=false;setFps(12);setSpeed(1);sync()}
function tick(now){if(playing)frame=(frame+Math.min(100,now-last)/1000*fps*speed)%totalFrames();last=now;$('#scrubber').value=Math.floor(frame);$('#frameReadout').textContent=`Frame ${String(Math.floor(frame)+1).padStart(2,'0')} / ${totalFrames()}`;$('#timeReadout').textContent=`${(frame/fps).toFixed(2)} s`;draw();requestAnimationFrame(tick)}
Object.values(controls).forEach(c=>c.oninput=sync);$$('[data-fps]').forEach(b=>b.onclick=()=>{setFps(+b.dataset.fps);draw()});$$('[data-speed]').forEach(b=>b.onclick=()=>setSpeed(+b.dataset.speed));$('#playBtn').onclick=()=>{playing=!playing;$('#playBtn').textContent=playing?'Ⅱ':'▶'};$('#prevFrame').onclick=()=>{playing=false;frame=(Math.floor(frame)-1+totalFrames())%totalFrames();draw()};$('#nextFrame').onclick=()=>{playing=false;frame=(Math.floor(frame)+1)%totalFrames();draw()};$('#scrubber').oninput=e=>{playing=false;frame=+e.target.value;draw()};$('#compareBtn').onclick=()=>{compare=!compare;$('#compareBtn').textContent=compare?'Hide rigid tail':'Compare rigid tail';draw()};$('#fullscreenBtn').onclick=()=>$('#canvasWrap').requestFullscreen?.();$('#arcToggle').onchange=$('#onionToggle').onchange=()=>draw();$('#explainToggle').onchange=()=>{if($('#explainToggle').checked&&speed>.25)setSpeed(.25);draw()};$('#resetAll').onclick=$('#resetControls').onclick=reset;$('#newPrompt').onclick=()=>{$('#promptText').textContent=prompts[++prompt%prompts.length]};$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===b));const [title,copy,tryText]=lessons[b.dataset.focus];$('#lessonTitle').textContent=title;$('#lessonCopy').textContent=copy;$('#tryThis').textContent=tryText});addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();$('#playBtn').click()}if(e.key==='ArrowLeft')$('#prevFrame').click();if(e.key==='ArrowRight')$('#nextFrame').click()});addEventListener('resize',resize);reset();resize();requestAnimationFrame(tick);
